config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'todos/index'

  get "todos/delete" => "todos#delete", :as => :delete

 get "todos/:id/edit" => "todos#edit", :as => :edit
  resources :todo do
    post :edit, on: :member
  end

  post "todos/add" => "todos#add"

  match 'todos/complete' => 'todos#complete', :via => :post

  patch 'todos/:id/update' => 'todos#update', :as => :update

  root 'todos#index'
end

app/models/todo.rb
# Authors: Brigham Diaz and Michael Banks
class Todo < ActiveRecord::Base
    attr_accessible :todo_item, :userEmail
    validates :todo_item, presence: true
end

app/models/user.rb
# Athors: Brigham Diaz and Michael Banks
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def new
        super
    end

    def create
        super
        # add custom create logic here
    end

    def update
        super
    end
end 

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_filter :authenticate_user!
  # index action initializes the todo_array, new todo and sends page to view
  def index
    @todo_array = Todo.where(:todos => { :userEmail => current_user.email })
    @new_todo = Todo.new
    render :index
  end

  # retrieves the todo object that passed from the edit link
  def edit
    @todo = Todo.find(params[:id])
  end

  # get the last item in Todo list and delete it
  def delete
    t = Todo.last
    t.delete
  end

  # updates the task that user has edited
  def update
    @todo = Todo.find(params[:id])
    # security feature - verifies that todo item variable is being passed
    if @todo.update(params.require(:todo).permit(:todo_item))
      flash[:success] = "Todo edited successfully"
      redirect_to :action => 'index'
    else
      render 'edit'
    end
  end

  # create a new todo item
  def add
    todo = Todo.create(:todo_item => params[:todo][:todo_item], :userEmail => current_user.email)
    # use model validation to verify textbox is not empty
    if !todo.valid?
        # If the form was empty we show an error message
        flash[:error] = todo.errors.full_messages.join("<br>").html_safe
    else
        # Otherwise we add the todos item and display a success message
        flash[:success] = "Todo added successfully"

    end
    redirect_to :action => 'index'
  end

  # mark todo item as complete
  def complete
    if params[:todos_checkbox].nil?
      flash[:error] = "You must check at least one todo item to complete"
    else
      # checkbox id will come here as an array so if items 1 and 2 are checked it will be [1, 2]
      params[:todos_checkbox].each do |check|
        todo_id = check
        t = Todo.find_by_id(todo_id)
        # update the status
        t.update_attribute(:completed, true)
      end
    end
    redirect_to :action => 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mbtodo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="navbar">
        <div class="navbar-inner">
            <a class="brand" href="#">Just Did it</a>
        </div>
    </div>
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>

<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<% # This is a form partial to reuse code for editing a todo item %>
<%= form_for @todo, url: update_path(@todo), method: :patch do |f| %>

    <p>
        <%= f.text_field :todo_item %>
    </p>

    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/todos/delete.html.erb
<%# Confirmation page that todo item was deleted %>
<p>Todo successfully deleted</p>
<%= link_to '<button class="btn-danger">Back</button>'.html_safe, todos_index_path %>

app/views/todos/edit.html.erb
<h1>Edit your todo</h1>
<div class="well">
    <%# when form is submitted the update_path method will be called with todo object passed in %>
    <%= render 'form' %>

    <%= link_to '<button class="btn-danger">Back</button>'.html_safe, todos_index_path %>
</div>

app/views/todos/index.html.erb
<div class="container">
    <div class="row">
        <div class="span4">
            <hr>
            <h1>ToDo</h1>

            <%= form_for @new_todo, :url => { :action => "add" }  do |f|  %>
                <%= f.text_field  :todo_item %>
                <%= f.submit "Add todo", class: "btn btn-primary" %>
                <%end%>

                <% if flash[:error] %>
                    <div class="alert alert-error">
                        <button type="button" class="close" data-dismiss="alert" >×</button>
                        <strong><%= flash[:error] %></strong>
                    </div>
                <% end %>

                <% if flash[:success] %>
                    <div class="alert alert-success">
                        <%= flash[:success] %>
                    </div>
                <% end %>

                <h3>ToDo's List</h3>
                <div class="well">
                    <%= form_tag("/todos/complete/", :method => "post") do %>
                        <ul style="list-style-type:none;">
                            <% @todo_array.each do |t| %>
                                <% if t.completed == true %>
                                    <%# every checkbox has the same 'name' attribute. the value of each checkbox is t.id#%>
                                    <li style="color:grey;"> <%= check_box_tag  "todos_checkbox[]",t.id %>  <strike><%= t.todo_item %></strike></li>
                                <% else %>
                                    <li> <%= check_box_tag  "todos_checkbox[]",t.id %> <%= t.todo_item %>
                                        <%= link_to 'Edit', edit_path(t) %>
                                    </li>
                                <% end %>
                            <% end %>
                        </ul>
                        <%= submit_tag("Complete Todos", :class=>"btn btn-success") %>
                    <% end %>
                    <%= link_to '<button class="btn-danger">Delete last todo</button>'.html_safe, delete_path %>
                </div>
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        </div>
    </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>